name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04        # ← actualiza runner; 20.04 se retira en 2025-04-15

    steps:
      # 1) Obtiene el código
      - name: Checkout code
        uses: actions/checkout@v4     # usa la versión más reciente

      # 2) Fecha de hoy como output
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"

      # 3) Caché global de Buildozer
      - name: Cache Buildozer global directory
        uses: actions/cache@v4        # v4 (o v3) — v2 ya no funciona
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # 4) Caché local del proyecto
      - name: Cache Buildozer local directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # 5) Compilar con Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1  # no hay v2; funciona con los runners nuevos
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      # 6) Subir el APK generado
      - name: Upload artifacts
        uses: actions/upload-artifact@v4          # v4 requerido
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

