name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROIDAPI: 30
      ANDROIDMINAPI: 21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Limpiar extraheader de git
        run: git config --unset-all http.https://github.com/.extraheader || true

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer local directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
      - name: Ensure Android SDK Command Line Tools and API 30 are installed
        run: |
          ANDROID_SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
          if ! find "$ANDROID_SDK_ROOT" -name sdkmanager -type f | grep -q .; then
            mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
            cd "$ANDROID_SDK_ROOT/cmdline-tools"
            wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
            unzip cmdline-tools.zip
            mv cmdline-tools latest
          fi
          SDKMANAGER=$(find "$ANDROID_SDK_ROOT" -name sdkmanager -type f | head -n 1)
          yes | "$SDKMANAGER" "platforms;android-30"
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
